version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 5000:80
    links:
      - fpm
      - db
    volumes:
      - ./html:/var/www/app

  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes:
      - ./html:/var/www/app
    links:
      - db

  db:
    image: mysql:5
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=appbank
      - MYSQL_PORT=33061

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pepa-linha
