version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 5000:80
    volumes:
      - ./public:/var/www/html
    links:
      - fpm

  fpm:
    build:
      context: .
      dockerfile: fpm.Dockerfile
    volumes:
      - ./public:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_database
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pepa-linha

volumes:
  db_data:
