version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 80:80
    links:
      - fpm
      - db
    volumes:
      - ./html:/var/www/app
      # - ./logs:/var/log/nginx
    networks:
      mynetwork:
        aliases:
          - mydev.dv

  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes:
      - ./html:/var/www/app
      # - ./docker/php.ini:/usr/local/etc/php/php.ini
    links:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password --sql-mode=NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appbank
      MYSQL_PORT: 33061
    networks:
      - mynetwork

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      # ADMINER_DESIGN: pepa-linha
      # ADMINER_DESIGN: konya
      ADMINER_DESIGN: brade
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
